# Generated by Django 4.2 on 2025-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_remove_payment_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.FloatField(),
        ),
    ]
