# Generated by Django 4.2 on 2025-10-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='plan',
            new_name='subscription_plan',
        ),
    ]
