# Generated by Django 4.2 on 2025-10-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_rename_plan_subscription_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchhistory',
            name='progress',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
